//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OAuthVk.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OAuthVk.Core.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла неизвестная ошибка..
        /// </summary>
        public static string ER1 {
            get {
                return ResourceManager.GetString("ER1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла внутренняя ошибка сервера..
        /// </summary>
        public static string ER10 {
            get {
                return ResourceManager.GetString("ER10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Один из необходимых параметров был не передан или неверен..
        /// </summary>
        public static string ER100 {
            get {
                return ResourceManager.GetString("ER100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недопустимый номер телефона..
        /// </summary>
        public static string ER1000 {
            get {
                return ResourceManager.GetString("ER1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер телефона занят другим пользователем..
        /// </summary>
        public static string ER1004 {
            get {
                return ResourceManager.GetString("ER1004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный API ID приложения..
        /// </summary>
        public static string ER101 {
            get {
                return ResourceManager.GetString("ER101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В тестовом режиме приложение должно быть выключено или пользователь должен быть залогинен..
        /// </summary>
        public static string ER11 {
            get {
                return ResourceManager.GetString("ER11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Превышено ограничение на число попыток, попробуйте позже..
        /// </summary>
        public static string ER1105 {
            get {
                return ResourceManager.GetString("ER1105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильный код..
        /// </summary>
        public static string ER1110 {
            get {
                return ResourceManager.GetString("ER1110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недопустимый пароль..
        /// </summary>
        public static string ER1111 {
            get {
                return ResourceManager.GetString("ER1111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обработка... Попробуйте позже..
        /// </summary>
        public static string ER1112 {
            get {
                return ResourceManager.GetString("ER1112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный идентификатор пользователя..
        /// </summary>
        public static string ER113 {
            get {
                return ResourceManager.GetString("ER113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недопустимое короткое имя страницы..
        /// </summary>
        public static string ER1260 {
            get {
                return ResourceManager.GetString("ER1260", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требуется ввод кода с картинки (Captcha)..
        /// </summary>
        public static string ER14 {
            get {
                return ResourceManager.GetString("ER14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступ запрещён..
        /// </summary>
        public static string ER15 {
            get {
                return ResourceManager.GetString("ER15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный timestamp. .
        /// </summary>
        public static string ER150 {
            get {
                return ResourceManager.GetString("ER150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требуется выполнение запросов по протоколу HTTPS, т.к. пользователь включил настройку, требующую работу через безопасное соединение..
        /// </summary>
        public static string ER16 {
            get {
                return ResourceManager.GetString("ER16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требуется валидация пользователя..
        /// </summary>
        public static string ER17 {
            get {
                return ResourceManager.GetString("ER17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страница удалена или заблокирована..
        /// </summary>
        public static string ER18 {
            get {
                return ResourceManager.GetString("ER18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приложение выключено..
        /// </summary>
        public static string ER2 {
            get {
                return ResourceManager.GetString("ER2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данное действие запрещено для не Standalone приложений..
        /// </summary>
        public static string ER20 {
            get {
                return ResourceManager.GetString("ER20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступ к альбому запрещён. Убедитесь, что Вы используете верные идентификаторы..
        /// </summary>
        public static string ER200 {
            get {
                return ResourceManager.GetString("ER200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступ к аудио запрещён. Убедитесь, что Вы используете верные идентификаторы..
        /// </summary>
        public static string ER201 {
            get {
                return ResourceManager.GetString("ER201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступ к группе запрещён.
        ///(Убедитесь, что текущий пользователь является участником или руководителем сообщества (для закрытых и частных групп и встреч)).
        /// </summary>
        public static string ER203 {
            get {
                return ResourceManager.GetString("ER203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данное действие разрешено только для Standalone и Open API приложений..
        /// </summary>
        public static string ER21 {
            get {
                return ResourceManager.GetString("ER21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Метод был выключен..
        /// </summary>
        public static string ER23 {
            get {
                return ResourceManager.GetString("ER23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требуется подтверждение со стороны пользователя..
        /// </summary>
        public static string ER24 {
            get {
                return ResourceManager.GetString("ER24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ключ доступа сообщества недействителен..
        /// </summary>
        public static string ER27 {
            get {
                return ResourceManager.GetString("ER27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ключ доступа приложения недействителен..
        /// </summary>
        public static string ER28 {
            get {
                return ResourceManager.GetString("ER28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Передан неизвестный метод..
        /// </summary>
        public static string ER3 {
            get {
                return ResourceManager.GetString("ER3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Альбом переполнен. (Перед продолжением работы нужно удалить лишние объекты из альбома или использовать другой альбом.).
        /// </summary>
        public static string ER300 {
            get {
                return ResourceManager.GetString("ER300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверная подпись..
        /// </summary>
        public static string ER4 {
            get {
                return ResourceManager.GetString("ER4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авторизация пользователя не удалась..
        /// </summary>
        public static string ER5 {
            get {
                return ResourceManager.GetString("ER5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действие запрещено. Вы должны включить переводы голосов в настройках приложения. (Проверьте настройки приложения: https://vk.com/editapp?id={0}&amp;section=payments).
        /// </summary>
        public static string ER500 {
            get {
                return ResourceManager.GetString("ER500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слишком много запросов в секунду..
        /// </summary>
        public static string ER6 {
            get {
                return ResourceManager.GetString("ER6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет прав на выполнение данных операций с рекламным кабинетом..
        /// </summary>
        public static string ER600 {
            get {
                return ResourceManager.GetString("ER600", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка при работе с рекламным кабинетом..
        /// </summary>
        public static string ER603 {
            get {
                return ResourceManager.GetString("ER603", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет прав для выполнения этого действия..
        /// </summary>
        public static string ER7 {
            get {
                return ResourceManager.GetString("ER7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный запрос..
        /// </summary>
        public static string ER8 {
            get {
                return ResourceManager.GetString("ER8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слишком много однотипных действий..
        /// </summary>
        public static string ER9 {
            get {
                return ResourceManager.GetString("ER9", resourceCulture);
            }
        }
    }
}
